### ISSUE TITLE
Disable Finish Button until required questions are completed

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-surveys#28]
Not sure if there is currently a variable for "required", but the finish button should either be disabled or not shown until the last page/all required questions completed.

**Comment by vsoch** [comment]
Could you provide more detail on this, it's not clear what you mean. Are you talking about the surveys? if so, the ability to proceed, etc, is something instilled in JsPsych, not in the expfactory infrastructure.

**Comment by vsoch** [comment]
This is done now that validation is working.
