### ISSUE TITLE
Surveys aren't registering that questions are answered

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-surveys#33]
Try entering an answer in [this survey](http://expfactory.github.io/cognitive_reflection_survey.html), for example. Even after entering 23 (for example) it says "Please answer all questions in red"

**Comment by vsoch** [comment]
Please look for issue in the survey.tsv file, there might be a page off or something like that.

**Comment by vsoch** [comment]
It would be helpful if you might be able to debug some of these issues, instead of just posting for me to do. :) a Thanks!

**Comment by IanEisenberg** [comment]
There are other people working on this project. Surveys have generally been @zenkavi's domain. I put these issues here to indicate problems that _someone_ can fix (it may be me).

**Comment by vsoch** [comment]
ah! This is actually easy to fix. The issue is that I made the validation for radio and checkboxes:

```
 $(".page10.required:checked").length
```

The fix is just to edit the html to look for required checked OR text fields filled. The code is in the expfactory-python surveys if you'd like to debug.

**Comment by IanEisenberg** [comment]
Ok. Thanks!

On Wed, Mar 30, 2016 at 5:52 PM, Vanessa Sochat notifications@github.com
wrote:

> ah! This is actually easy to fix. The issue is that I made the validation
> for radio and checkboxes:
> 
>  $(".page10.required:checked").length
> 
> The fix is just to edit the html to look for required checked OR text
> fields filled. The code is in the expfactory-python surveys if you'd like
> to debug.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-surveys/issues/33#issuecomment-203699404

## 

Best,
Ian

**Comment by IanEisenberg** [comment]
I'm trying to figure out where the validation is defined. Mind verifying if I am on the right track? 

So I see [this page](https://github.com/expfactory/expfactory-python/blob/master/expfactory/templates/survey.html#L56) which takes a validation in from [here](https://github.com/expfactory/expfactory-python/blob/master/expfactory/views.py#L405). That validation to sub in is returned using [generate_survey](https://github.com/expfactory/expfactory-python/blob/master/expfactory/survey.py#L414), which relies on parse_validation, which relies on parse_questions.

Is the issue with [this line](https://github.com/expfactory/expfactory-python/blob/master/expfactory/survey.py#L241)? That's quite the hairy line, but I'll start diving into it as soon as you let me know I'm on the right track :)

**Comment by vsoch** [comment]
Yes, the validation is produced by the function `parse_validation`. As it is now, it takes in a dictionary of counts and prints an equivalent line per page to verify that the number of checked options is equivalent to the number of required. Before you edit the code producing the validation, I would recommend generating a static version of a survey with different question types, and getting the javascript just right there. Once you have that working, then it makes sense to try and reproduce the same thing in expfactory-python. Otherwise, you have no way of knowing what you should add to the function.

**Comment by vsoch** [comment]
It's also not as hairy as it seems, it's just printing a string with different variables in it that matches the javascript that works for the validation :) Don't worry too much about this unless you have the overhead, I'll probably get to it this weekend, but I want to get surveys and games integrated into expfactory first.

**Comment by IanEisenberg** [comment]
It's good for me to get a handle on things (at least a bit). You'll be going off into the big bad world - I'll need to debug, at least a bit. Anyway, [here's a fix](https://github.com/IanEisenberg/expfactory-python/blob/validation_fix/expfactory/survey.py#L241) ... I think. I'm not sure what the "is_required" line is doing or where it comes from. If it's fine I'll send a PR. Otherwise, sure, over the weekend would be great.

**Comment by vsoch** [comment]
all surveys have been updated, please test.

**Comment by IanEisenberg** [comment]
Reference for later: Currently validation is done by making sure the number of checks + non-empty fields equals the number of required questions. @zenkavi, will you be able to look into these issues?

Problems arise if there are multiple checkboxes in one question, like in the [demographics survey](http://expfactory.github.io/demographics_survey.html). On the first page of questions (page 3) there are multiple options for race. If you choose the right amount, you can continue (as long as the text fields are filled in).

I noticed that if the textfields are empty, I cannot proceed because the form tells me "This field is required". Not sure if there is a way to add that to checkboxes/numbers.

Final issue - on tasks like the cognitive reflection task the field correctly alerts me if my response is "not a number" as required, but let's me proceed anyway. It should prevent progression unless the field is filled correctly.

**Comment by vsoch** [comment]
I wrote the entire validation, so these extra functionalities that you want need to be added to the code. Why don't you give another go at it.

**Comment by IanEisenberg** [comment]
Yeah, I plan to!
