### ISSUE TITLE
Mturk bug - Uncaught SyntaxError: Unexpected token class

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-surveys#34]
Uncaught SyntaxError: Unexpected token class: line 74
![screenshot from 2016-03-30 21 25 09](https://cloud.githubusercontent.com/assets/9325440/14165451/e82a2fd6-f6bd-11e5-91ee-dc5895c668d4.png)

It looks like the function wasn't closed but I have no idea where/how this html is generated to debug.

**Comment by vsoch** [comment]
This isn't finished being developed yet...

**Comment by IanEisenberg** [comment]
Ah! Sorry, had no idea where the surveys were at.

**Comment by vsoch** [comment]
Please don't test any of the surveys or games using expfactory-docker. This hasn't been written let alone tested, and it could have unintended consequences. The mturk part will not be developed or tested until saving of data is resolved using the local dummy version. When the integration is complete I will close the relevant issues and let everyone know.

**Comment by vsoch** [comment]
np!

**Comment by vsoch** [comment]
Here are the relevant issues:

https://github.com/expfactory/expfactory-docker/issues/96#issuecomment-203707367
https://github.com/expfactory/expfactory-docker/issues/90
https://github.com/expfactory/expfactory-docker/issues/91
