### ISSUE TITLE
More data needs to be added to the data output by surveys

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-surveys#35]
While the surveys are currently _much_ more beautiful, they don't save nearly as much data as the previous ones did. Right now they record the scored choice that the person made, and that's it. (For @zenkavi) Reverse scoring is taken care of by defining "option_values" in a survey's .tsv [see here](https://github.com/IanEisenberg/expfactory-surveys/blob/master/bis11_survey/survey.tsv)

Minimum data we need:
-The actual choice the person made. So if they chose the first option, we need to know that.
-Response range (scored out of what?). This can just be the whole option field to allow for non-likert like scales (option text may be [3,4,17] or something else wonky)
-The question text 

Other things that @zenkavi recorded that was nice:
-Reaction time per page of the survey
-stim_response text
-times viewed (I presume that's the number of times someone visits a page if they use the back button)

@zenkavi, I don't have the bandwidth to deal with this, at least not alone. Could you own this (and we need the surveys fixed ASAP). I'm happy to meet up so we can work on it together. @vsoch, could you point us in the right direction? Where is the dictionary returned [here](https://github.com/expfactory/expfactory-docker/blob/caf007eeaf66486d6d65956b350a10157961c636/expdj/apps/experiments/views.py#L477) defined.

**Comment by vsoch** [comment]
You are looking at old data, I just added a function that exports absolutely everything.

**Comment by IanEisenberg** [comment]
The actual question isn't added to the data, and we'll want total time taken on the survey.

**Comment by vsoch** [comment]
Question has been added. For total time, I'll open another issue.
