### ISSUE TITLE
three surveys missing responses

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-surveys#43]
the number of responses / values are misaligned for three questions in a survey:

![image](https://cloud.githubusercontent.com/assets/814322/14430246/a28d907a-ffb5-11e5-987e-25bbf7d080e4.png)

easiest way to find would be programatically

**Comment by IanEisenberg** [comment]
Thanks. I'll fix ASAP

On Monday, April 11, 2016, Vanessa Sochat notifications@github.com wrote:

> the number of responses / values are misaligned for three questions in a
> survey:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/814322/14430246/a28d907a-ffb5-11e5-987e-25bbf7d080e4.png
> 
> easiest way to find would be programatically
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-surveys/issues/43

## 

Best,
Ian

**Comment by vsoch** [comment]
I'm going to write a test for this, it will be performed during continuous integration.

**Comment by IanEisenberg** [comment]
Sounds good.

On Mon, Apr 11, 2016 at 9:53 AM, Vanessa Sochat notifications@github.com
wrote:

> I'm going to write a test for this, it will be performed during continuous
> integration.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-surveys/issues/43#issuecomment-208447640

## 

Best,
Ian

**Comment by vsoch** [comment]
ok, found the bug, will push the PR for validation function testing in CI and fix to the survey soon.

**Comment by vsoch** [comment]
![image](https://cloud.githubusercontent.com/assets/814322/14436645/8a3923be-ffd2-11e5-9eef-4e21f800a389.png)

**Comment by IanEisenberg** [comment]
Nice!
