### ISSUE TITLE
Interested in contributing surveys

### ISSUE THREAD

**Issue by juhng62** [expfactory/expfactory-surveys#67]
Hi. I'd like to contribute surveys but I am a bit confused.

1. Where am I supposed to contribute surveys?

https://github.com/expfactory/expfactory-experiments

or https://github.com/expfactory-experiments

or https://github.com/expfactory/expfactory-surveys

or anywhere else?

If the first one, how do I request a pull?

2. It seems there are two different formats for config.json. Which one am I supposed to follow?

https://github.com/expfactory/expfactory-surveys/blob/master/bis11_survey/config.json

or https://expfactory.github.io/contribute

If the second one, how do I write url before my pull request is accepted?

3. Is there anything else to write apart from config.json and survey.tsv for contribution?

Thanks in advance!

**Comment by vsoch** [comment]
@juhng62 there are two versions of the project - the first that deploys to expfactory.org (using mturk) is associated with the surveys repository https://github.com/expfactory/expfactory-surveys. E.g., to deploy an experiment to expfactory.org you'd add a survey there, or an experiment to https://github.com/expfactory/expfactory-experiments.

If you want to create a reproducible experiment container, for use with the second version of the project, all of those experiments and surveys live in https://github.com/expfactory-experiments, and those are the docs associated with https://expfactory.github.io/. It's a second go at the project that I did after graduate school, and you are correct that the config, etc. is slightly different, but I took all the previous experiments and made them modular there.

So - where to contribute is up to you! For the first, you can chat with @rwblair that is still with Poldracklab and running the show. For the second, you can really just create an experiment repository anywhere, and ping me on an issue and I'll help you to add it to the new expfactory library, and I'd be happy to create you a repository in the expfactory-experiments org.

Sorry for the confusion! That's probably my fault for re-doing the project, but the original wasn't completing the original vision I had to make a resource available for anyone to use.
